export { default as LeftSide } from "./left-side/LeftSide";
export { default as RightSide } from "./right-side/RightSide";
export { default as MiddleSide } from "./middle-side/MiddleSide";
export { default as Movies } from "./movies/Movies";
export { default as Header } from "./header/Header";
export { default as HeroSlide } from "./hero-slide/HeroSlide";
export { default as Button } from "./button/Button";

export { TransparentButton } from "./button/Button";
export { default as NextArrow } from "./next-arrow/NextArrow";
export { default as PrevArrow } from "./prev-arrow/PrevArrow";
export { default as MovieList } from "./movie-list/MovieList";
export { default as MovieCard } from "./movie-card/MovieCard";
export { default as HeaderLogo } from "./header-logo/HeaderLogo";
export { default as Input } from "./input/Input";
export { CardSmall } from "./movie-card/MovieCard";
export { default as StandingList } from "./standing-list/StandingList";
export { default as Modal } from "./modal/Modal";
export { ModalContent } from "./modal/Modal";
export { default as Footer } from "./footer/Footer";
export { default as Videos } from "./videos/Videos";
export { default as Review } from "./review/Review";
export { default as MovieGrid } from "./movie-grid/MovieGrid";
export { default as CatalogSlide } from "./catalog-slide/CatalogSlide";
